---
title: "TidyTuesdayAnimatedCharts"
author: "Andrew Couch"
date: "7/28/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(gganimate)
library(gifski)

df <- read.csv("police_allegations.csv")

df %>% head()
```

```{r}
violation_ts <- df %>% 
  select(year_received, allegation = fado_type, result = board_disposition) %>% 
  mutate(result = case_when(
    str_detect(result, "Substantiated") ~ "Violation",
    str_detect(result, "Exonerated") ~ "Violation",
    TRUE ~ "No_Violation"
  )) %>% 
  group_by(year_received) %>% 
  count(allegation, result) %>% 
  ungroup() %>% 
  arrange(year_received, allegation, result) %>% 
  ggplot(aes(x = year_received, y = n, color = allegation)) + 
  geom_line() + 
  geom_point() + 
  facet_wrap(~result, scales = "free_y") + 
  theme(legend.position = "top") + 
  transition_reveal(year_received)

animate(violation_ts, renderer = gifski_renderer())

```

```{r}
df <- df %>% 
  mutate(result = case_when(
    str_detect(board_disposition, "Substantiated") ~ "Violation",
    str_detect(board_disposition, "Exonerated") ~ "Violation",
    TRUE ~ "No_Violation"
  ))


disposition_result <- df %>% 
  select(result, year_received) %>% 
  count(year_received, result) %>% 
  ggplot(aes(x = result, y = n, fill = result)) + 
  geom_col() + 
  theme(legend.position = "none") + 
  transition_time(year_received) + 
  labs(title = "Year: {frame_time}")


animate(disposition_result, renderer = gifski_renderer())
```


```{r}
precinct_dist <- df %>% 
  select(precinct, unique_mos_id, fado_type) %>% 
  group_by(precinct) %>% 
  count(unique_mos_id, fado_type) %>% 
  ungroup() %>% 
  ggplot(aes(x = n, fill = fado_type)) + 
  geom_histogram() + 
  theme(legend.position = "none") + 
  facet_wrap(~fado_type, scales = "free_y") + 
  scale_x_sqrt() + 
  transition_states(precinct,
                    transition_length = 2,
                    state_length = 1) + 
  labs(title = "Precinct: {closest_state}") + 
  enter_fade() + 
  exit_shrink()

animate(precinct_dist, renderer = gifski_renderer())
```

```{r}


rank_allegations <- df %>% 
  select(rank_incident, year_received, result) %>% 
  group_by(year_received, rank_incident) %>% 
  count(rank_incident, result) %>% 
  ungroup() %>% 
  arrange(year_received, rank_incident, result) %>% 
  pivot_wider(names_from = result, values_from = n, values_fill = 0) %>% 
  ggplot(aes(x = No_Violation, y = Violation, color = rank_incident)) + 
  geom_abline(slope = 1, intercept = 0) + 
  geom_point(size = 10) + 
  theme(legend.position = "top") + 
  transition_time(year_received) + 
  shadow_wake(wake_length = .1, alpha = FALSE) + 
  labs(title = "Year: {frame_time}",
       subtitle = "Points below the line means majority of allegations were false \npoints above the line means majority of allegations were true",
       color = "")

animate(rank_allegations, renderer = gifski_renderer())
```














