---
title: "TidyTuesdayComputerVisionHelloWorld"
author: "Andrew Couch"
date: "5/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(keras)
library(tidymodels)


mnist_data <- keras::dataset_mnist()
image_data <- mnist_data$train$x
image_labels <- mnist_data$train$y
image_data %>% dim()
```

```{r}
#Refromat images to tabular format
image_data <- array_reshape(image_data, dim = c(60000, 28*28))
image_data %>% dim()
```

```{r}

image_data <- image_data[1:10000,]
image_labels <- image_labels[1:10000]
#Perform T-sne
library(Rtsne)
image_data <- normalize_input(image_data)
tsne_df <- Rtsne(image_data, perplexity = 25, dims = 3)

```

```{r}
library(plotly)
#Visualize the embeddings using plotly
plotly_df <- as_tibble(tsne_df$Y) %>% 
  cbind(image_labels) %>% 
  mutate(labels = image_labels) %>% 
  mutate(labels = as.factor(labels))

plot_3d <- plot_ly(plotly_df, x = ~V1, y = ~V2, z = ~V3, color = ~labels) %>% 
  add_markers()

htmlwidgets::saveWidget(plot_3d, file = "tnse_plot.html")
```



```{r}
#Create model data and partition into train and test 
model_data <- plotly_df %>% select(-image_labels)


tidy_split <- initial_split(model_data, prop = .8)
tidy_train <- training(tidy_split)
tidy_test <- testing(tidy_split)
```

```{r}
#Create a recipe for pre-processing
tidy_rec <- recipe(labels~., data = tidy_train) %>% 
  step_center(all_predictors()) %>% 
  step_scale(all_predictors())

tidy_prep <- prep(tidy_rec)
tidy_juice <- juice(tidy_prep)
```



```{r}
#Training models 
wf <- workflow() %>% 
  add_recipe(tidy_rec)

#Create a knn model
tidy_knn <- nearest_neighbor(neighbors = tune()) %>% 
  set_mode("classification") %>% 
  set_engine("kknn")

#Create a baseline model
tidy_logistic <- multinom_reg(penalty = tune(), mixture = tune()) %>% 
  set_mode("classification") %>% 
  set_engine("glmnet")
  
```

```{r}
#Create a grid for the models
#Knn grid
knn_grid <- grid_regular(neighbors(), levels = 10)

#Baseline grid
logistic_grid <- grid_regular(penalty(), mixture(), levels = 10)
```


```{r}
#Create k-folds dataset
tidy_kfolds <- vfold_cv(tidy_train, v = 10)


logistic_tune <- tune_grid(
  wf %>% add_model(tidy_logistic),
  resamples = tidy_kfolds,
  grid = logistic_grid
)

knn_tune <- tune_grid(
  wf %>% add_model(tidy_knn),
  resamples = tidy_kfolds,
  grid = knn_grid
)

```

```{r}
logistic_tune %>% 
  collect_metrics() %>% 
  filter(.metric == "accuracy") %>% 
  select(penalty, mixture, mean) %>% 
  pivot_longer(-mean) %>% 
  ggplot(aes(x = value, y = mean)) + geom_line() + facet_wrap(~name, scales = "free")
```

```{r}
knn_tune %>% 
  collect_metrics() %>% 
  filter(.metric == "accuracy") %>% 
  ggplot(aes(x = neighbors, y = mean)) + geom_line()
```


```{r}
#Create new models with final parameters
tidy_logistic <- finalize_model(tidy_logistic, logistic_tune %>% select_best("accuracy"))

tidy_knn <- finalize_model(tidy_knn, knn_tune %>% select_best("accuracy"))


tidy_logistic
tidy_knn
```

```{r}
wf %>% add_model(tidy_logistic) %>% last_fit(tidy_split) %>% collect_metrics()
```


```{r}
wf %>% add_model(tidy_knn) %>% last_fit(tidy_split) %>% collect_metrics()
```

























