---
title: "TidyTuesdayCO2Emissions"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
food_consumption <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv')
```


```{r}
#Viewing the basic summary of the dataset 
#Many countries and 11 food categories
food_consumption %>% 
  summary()
```

```{r}
#Distributions of CO2 and Consumption are not as proportional as I would imagine
options(scipen = 999)
food_consumption %>% 
  gather(key = "feature", value = "value", -country, -food_category) %>% 
  ggplot(aes(x = feature, y = value, color = feature)) + 
  geom_boxplot() +
  facet_wrap(~feature, scales = "fixed") + 
  scale_y_log10()
```


```{r}
food_consumption %>% 
  gather(key = "feature", value = "value", -country, -food_category) %>% 
  ggplot(aes(x = feature, y = value, color = feature)) + 
  geom_boxplot() +
  geom_jitter(alpha = .1) + 
  facet_wrap(~feature, scales = "fixed") + 
  scale_y_log10()
```



```{r}
#Consumption = Kg ate by each person / year
#CO2 Emission = Kg of CO2 produced by each person / year

#Consumption = Kg ate by each person
#CO2 Emission = Kg of CO2 produced by each person


#For every Kg of CO2 emitted how many Kgs of food do they eat? 
#Or Kgs of Food eaten produces how many Kgs of CO2? 





food_consumption %>% 
  filter(consumption != 0) %>% 
  mutate(co2perfood = co2_emmission/consumption) %>% 
  group_by(food_category) %>% 
  summarise(avg_c02perfood = mean(co2perfood)) %>% 
  ggplot(aes(x = reorder(food_category, avg_c02perfood), y = avg_c02perfood, fill = food_category)) + 
  geom_col() + 
  coord_flip() + 
  theme(legend.position = "none")

#Lamb & Goat is inefficient and should be avoided
#Same with beef but mostly everyone knows this 
#Rice is more inefficient than Wheat? 

```

```{r}
food_consumption %>% 
  select(-country) %>% 
  gather(key = "feature", value = "value", -food_category) %>% 
  ggplot(aes(x = food_category, y = value, color = food_category)) +
  geom_boxplot() + 
  scale_y_log10() +
  facet_wrap(~feature, scales = "fixed") + 
  coord_flip() +
  theme(legend.position = "none")
```

```{r}
food_consumption %>% 
  group_by(food_category) %>%  
  summarise(consumption = mean(consumption),
            co2_emmission = mean(co2_emmission)) %>% 
  ggplot(aes(x = consumption, y = co2_emmission, color = food_category)) + 
  geom_point() + 
  geom_abline(slope = 1) + 
  scale_x_log10() + 
  scale_y_log10()
```

```{r}
food_consumption %>% 
  group_by(food_category) %>%  
  summarise(consumption = mean(consumption),
            co2_emmission = mean(co2_emmission)) %>% 
  mutate(residuals = co2_emmission-consumption) %>% 
  ggplot(aes(x = consumption, y = co2_emmission, color = food_category)) + 
  geom_point() + 
  geom_segment(aes(xend = consumption, yend = consumption, x = consumption, y = co2_emmission)) + 
  geom_abline(slope = 1) + 
  scale_x_log10() + 
  scale_y_log10()
  
```



```{r}
#Top 5 consumers of each food category
food_consumption %>% 
  group_by(food_category) %>% 
  top_n(consumption, n = 5) %>% 
  arrange(food_category, -consumption) 

```

```{r}
#Coutries that appear more than once in the top 5 consumers by food category
food_consumption %>% 
  group_by(food_category) %>% 
  top_n(consumption, n = 5) %>% 
  arrange(food_category, -consumption) %>% 
  ungroup() %>% 
  count(country, sort = TRUE) %>% 
  filter(n != 1)


```

```{r}
#T test between animal and non animal for consumption and co2 emission 
library(broom)
food_consumption %>% 
  mutate(vegan = if_else(food_category %in% c("Wheat and Wheat Products", "Rice", "Soybeans", "Nuts inc. Peanut Butter"), "Non-Animal Product", "Animal Product")) %>% 
  select(consumption, co2_emmission, vegan) %>% 
  gather(key = "type", value = "value", -vegan) %>% 
  mutate(type = as.factor(type),
         vegan = as.factor(vegan)) %>%
  group_by(type) %>% 
  do(test = t.test(value~vegan, data = (.))) %>% 
  tidy(test) %>% 
  ggplot(aes(x = type, y = p.value)) + geom_col() + geom_hline(yintercept = .05) 
```

```{r}

food_consumption %>% 
  mutate(vegan = if_else(food_category %in% c("Wheat and Wheat Products", "Rice", "Soybeans", "Nuts inc. Peanut Butter"), "Non-Animal Product", "Animal Product")) %>%
  group_by(country) %>% 
  top_n(consumption, n = 1) %>% 
  group_by(food_category) %>% 
  count(vegan, sort = TRUE)

```

```{r}
food_consumption %>% 
  mutate(vegan = if_else(food_category %in% c("Wheat and Wheat Products", "Rice", "Soybeans", "Nuts inc. Peanut Butter"), "Non-Animal Product", "Animal Product")) %>%
  gather(key = "feature", value = "value", -country, -food_category, -vegan) %>% 
  select(-country) %>% 
  ggplot(aes(x = value, fill = vegan)) + 
  geom_density(alpha = .3) + 
  scale_x_log10() + 
  facet_wrap(~feature, scale = "free", nrow = 2) 
```






