---
title: "TidyTuesdayFunctions"
author: "Andrew Couch"
date: "7/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
animal_outcomes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-21/animal_outcomes.csv')
animal_complaints <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-21/animal_complaints.csv')
brisbane_complaints <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-21/brisbane_complaints.csv')

```

```{r}
animal_outcomes
animal_complaints
brisbane_complaints
```

```{r}
animal_complaints 

my_first_function <- function(){
  print("Hello World")
}

my_first_function()

#Clean data using a helper/lambda function
animal_complaints <- animal_complaints %>% 
  rename_all(.funs = function(.x){
    .x %>% tolower() %>% str_replace(pattern = " ", replacement = "_")
  })

```


```{r}

convert_to_decimal <- function(value, total){
  return(value/total)
}

#Apply function across columns using Across
animal_outcomes %>% 
  mutate(across(ACT:WA, ~convert_to_decimal(value = .x, total = Total)))

#Create a function that is pipeable that does the same thing 
convert_area_to_decimal <- function(df){
  
  df %>% mutate(across(ACT:WA, ~convert_to_decimal(value = .x, total = Total)))

}

#Looks cleaner and does the same thing 
animal_outcomes %>% convert_area_to_decimal()


#Another to create the same function 

tidy_area_percent <- . %>% mutate(across(ACT:WA, ~convert_to_decimal(value = .x, total = Total)))

animal_outcomes %>% tidy_area_percent()
```

```{r}

#Tidy Eval 


create_bar_chart <- function(column_var, df){
  
  column_var <- enquo(column_var)
  
  df %>% 
    select(!!column_var) %>% #Must add bang-bang
    count(!!column_var) %>% 
    mutate(!!column_var := reorder(!!column_var, n)) %>% #Also use := instead of = for
    ggplot(aes(x = !!column_var, y = n, fill = !!column_var)) + 
    geom_col() + 
    coord_flip() + 
    theme(legend.position = "none")
  
}

create_bar_chart(outcome, animal_outcomes)

```

```{r}

#Make a function that create a chart for each suburb and saves it as a pdf.

save_charts <- function(df, filename){
  
  temp_chart <- df %>% 
    mutate(category = reorder(category, n)) %>% 
    ggplot(aes(x = category, y = n, fill = category)) + 
    geom_col() + 
    coord_flip() + 
    theme(legend.position = "none") + 
    ggtitle(paste0(filename, " Attacks"))
  
  ggsave(filename = paste0(filename, ".pdf"), plot = temp_chart, width = 11, height = 8.5, units = "in")
  
  
}


library(magrittr)

brisbane_complaints %>% 
  filter(animal_type == "Attack") %>% 
  count(suburb, category) %>% 
  drop_na() %>% 
  nest(-suburb) %>% 
  slice(1:10) %>% #Changed to only saving 10 pdfs 
  mutate(suburb = str_replace(suburb, " ", "_")) %$% 
  walk2(data, suburb, save_charts)


  
```


















