---
title: "TidyTuesdayTitanic"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)

df <- read.csv("titanic.csv")
df %>% summary()
```

```{r}
#Row wise counts of na's
df %>%
  mutate(row_key = row_number()) %>% 
  gather(key = "key", value = "value", -row_key) %>% 
  filter(value %>% is.na()) %>% 
  count(row_key, sort = TRUE)
```



```{r}
df %>% group_by(Pclass) %>% 
  summarise(count = n(),
            min_fare = min(Fare, na.rm = TRUE),
            avg_age = mean(Age, na.rm = TRUE),
            avg_fare = mean(Fare, na.rm = TRUE))
```


```{r}
#Step knn-impute
df %>% filter(Pclass %>% is.na())
```


```{r}
#But first we need to clean
df <- df %>% 
  select(-Name) %>% 
  mutate(Sex = as.factor(Sex),
         Survived = as.factor(Survived),
         Pclass = as.factor(Pclass))

titanic_rec <- recipe(Survived ~., data = df)

titanic_rec <- titanic_rec %>% 
  step_knnimpute(Pclass)
```


```{r}
df %>% group_by(Sex) %>% 
  summarise(avg_age = mean(Age, na.rm = TRUE),
            avg_fare = mean(Fare, na.rm = TRUE))


df %>% filter(Sex %>% is.na())

#Impute the modal categorical value

titanic_rec <- titanic_rec %>% 
  step_modeimpute(Sex)
```

```{r}
df %>% 
  ggplot(aes(Age)) + 
  geom_density()

#Impute using median age 

titanic_rec <- titanic_rec %>% 
  step_medianimpute(Age)

```

```{r}
df %>% 
  select(Siblings.Spouses.Aboard, Parents.Children.Aboard) %>% 
  gather() %>% 
  ggplot(aes(x = value, color = key)) + 
  geom_histogram() + 
  facet_wrap(~key, scales = "free")

#Since you cannot have a half a parent or sibling aboard lets impute with mode
titanic_rec <- titanic_rec %>% 
  step_modeimpute(Siblings.Spouses.Aboard, Parents.Children.Aboard)

```

```{r}
df %>% ggplot(aes(x = Fare)) + geom_density() + scale_x_log10()

df %>% select(Fare) %>% summary()
#Impute fare with the median value strong suspision that it is 3 or 2nd class 
#Scratch that impute using mean since the Pclass is 2nd class 
df %>% filter(Fare %>% is.na())

titanic_rec <- titanic_rec %>% 
  step_meanimpute(Fare)

```


```{r}
df %>% select_if(negate(is.factor)) %>% gather() %>% 
  ggplot(aes(x = value, fill = key)) + geom_histogram() + facet_wrap(~key, scales = "free")
```

```{r}
#Finished imputing now lets put in some dummyvars
titanic_rec <- titanic_rec %>% 
  step_dummy(Pclass, Sex)


```

```{r}
#Normalization 

titanic_rec <- titanic_rec %>% 
  step_normalize(all_numeric)


```



```{r}
#Finally prep and bake the recipe


titanic_prep <- recipe(Survived ~., data = df) %>%
  step_meanimpute(Fare) %>%
  step_medianimpute(Age, Siblings.Spouses.Aboard, Parents.Children.Aboard) %>%
  step_modeimpute(Sex) %>%
  step_knnimpute(Pclass) %>%
  step_normalize(all_numeric()) %>% 
  step_dummy(Pclass, Sex) %>%
  prep(strings_as_factors = FALSE) 


processed_df <- bake(titanic_prep, df)
processed_df <- processed_df %>% drop_na()
processed_df
```

