---
title: "TidyTuesday Password 1/14/2020"
author: "Andrew Couch"
date: "1/20/2020"
output: rmarkdown::github_document
---

```{r}
library(tidyverse)
passwords <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv')
passwords %>% 
  glimpse()

passwords <- passwords %>% na.omit()
```



```{r}
passwords %>% 
  select(value, time_unit) %>% 
  group_by(time_unit) %>% 
  summarise(mean = mean(value),
            n = n()) %>% 
  arrange(-n)

#Most passwords take days to crack 
```


```{r}
passwords %>% 
  select(value, time_unit) %>% 
  group_by(time_unit) %>% 
  summarise(n = n()) %>% 
  ggplot(aes(x = reorder(time_unit, -n), y = n, fill = time_unit)) + 
  geom_col()
```


```{r}
#Convert value to minutes for each group, create a conversion data frame and use a join 

#MinuteDf contains minutes for each single unit 
minuteDf <- data.frame(date = c("years", "months", "weeks", "days", "hours", "minutes", "seconds"), marginalminutes = c(365*24*60, 31*24*60, 7*24*60, 24*60, 60, 1, 1/60))


passwords <- passwords %>% 
  left_join(minuteDf, by = c("time_unit" = "date")) %>% 
  mutate(minutes = value*marginalminutes)
```
```{r}
#Which categories are weakest? 
passwords %>% 
  select(minutes, category) %>% 
  group_by(category) %>% 
  mutate(median = median(minutes)) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(category, median), y = minutes, color = category)) + 
  geom_boxplot() + 
  geom_jitter(alpha = .2) + 
  scale_y_log10() + 
  theme(axis.text.x = element_text(angle = 90)) + 
  xlab("")

```

```{r}
#Looking at sumamry statistics of categories and their respective minutes 
passwords %>% 
  select(minutes, category) %>% 
  group_by(category) %>% 
  summarise(sd = sd(minutes), 
            mean = mean(minutes),
            median = median(minutes),
            max = max(minutes), 
            min = min(minutes),
            n = n()) %>% 
  arrange(-median , -sd)


#Why do nerdy-pop have the highest median time? 
#Why does rebellioius-rude passwords have the highest minimum time to crack? 
```

```{r}
#Viewing top 5 passwords from those categories 
passwords %>% 
  select(category, password, minutes, value, time_unit) %>% 
  filter(category %in% c("nerdy-pop", "rebellious-rude")) %>% 
  group_by(category) %>% 
  top_n(minutes, n = 5) %>% 
  arrange(category, -minutes)


#Rebellious-rude do not have any numbers, also whatever and butthead take 3631896 minutes or 6.91 years to crack?
#I believe these may be outliers for how online guessing works 
```

```{r}
#Looking at the hardest passwords by looking at the top 25 highest times for time to crack by online guessing
passwords %>% 
  select(password, minutes, value, time_unit) %>% 
  top_n(minutes, n = 25) %>% 
  arrange(-minutes)


#Data contains popular weak passwords which makes sense however, it is odd seeding password to take 6.91 years of online guessing 
```

```{r}
#Lets look at time to crack offline in seconds 
#Is this from brute force or what? 

passwords %>% 
  select(password, offline_crack_sec) %>% 
  top_n(offline_crack_sec, n = 25) %>% 
  arrange(-offline_crack_sec)

```

```{r}
#Lets see what is passwords are shared and not shared between top 25 online guessing and offline crack offline 

topMinutes <- passwords %>% 
  select(password, minutes) %>% 
  top_n(minutes, n = 25) %>% 
  select(password) 
  
topOffline <- passwords %>% 
   select(password, offline_crack_sec) %>% 
   top_n(offline_crack_sec, n = 25) %>% 
   select(password)

#Share the same passwords
intersect(topMinutes, topOffline)
#No different passwords betweeen the two 
setdiff(topMinutes, topOffline)
```

```{r}
#Can I make a model to predict the time it would take to guess the password online or offline? 
modelDf <- passwords %>% 
  select(password) %>% 
  mutate(character = str_split(password,"")) %>% 
  unnest(character) %>% 
  count(password, character) %>% 
  spread(key = character, value = n) %>% 
  mutate_if(is.numeric, funs(replace_na(., 0))) %>% 
  left_join(passwords %>% select(password, minutes), by = c("password" = "password")) %>% 
  select(-password)
  
```

```{r}
library(caret)
dataPartition <- createDataPartition(modelDf$minutes, p = .8, list = FALSE)
trainData <- modelDf[dataPartition,]
testData <- modelDf[-dataPartition,]
```

```{r}
#We are using the characters and numbers to predict how many minutes it takes to guess the password online 
#This is a simple regression problem 
#Lets first create a linear model and see what going on

baseLineModel <- train(minutes~., 
                       data = trainData, 
                       method = "glm")

baseLineModel$finalModel %>% plot()
baseLineModel %>% varImp()
```

```{r}

predict(baseLineModel, testData) %>% 
  cbind(testData$minutes) %>% 
  as.tibble() %>% 
  rename("Pred" = 1, "Actual" = 2) %>% 
  ggplot(aes(x = Pred, y = Actual)) + 
  geom_point() +
  geom_smooth(se = FALSE, method = "lm") + 
  scale_y_log10() 

#Linear Model is not very good 
```

```{r}
#More EDA 
#What are the most common characters? 
passwords %>% 
  select(password) %>% 
  mutate(character = str_split(password,"")) %>% 
  unnest(character) %>% 
  count(password, character) %>% 
  mutate_if(is.numeric, funs(replace_na(., 0))) %>% 
  arrange(password, character) %>%
  group_by(character) %>% 
  summarise(n = sum(n)) %>% 
  ggplot(aes(x = reorder(character, -n), y = n)) + 
  geom_col()
```

```{r}
#what are the common letters for each category? 
passwords %>% 
  select(password) %>% 
  mutate(character = str_split(password,"")) %>% 
  unnest(character) %>% 
  count(password, character) %>% 
  mutate_if(is.numeric, funs(replace_na(., 0))) %>% 
  arrange(password, character) %>% 
  left_join(passwords %>% select(password, category), by = c("password"="password")) %>% 
  group_by(category, character) %>% 
  summarise(n = sum(n)) %>% 
  top_n(n, n = 10) %>% 
  ggplot(aes(x = character, y = n, fill = category)) + 
  geom_col() + 
  facet_wrap(~category, scales = "free") + 
  theme(legend.position = "none")
```

```{r}
#Zipfs Law? 
passwords %>% 
  select(password) %>% 
  mutate(character = str_split(password,"")) %>% 
  unnest(character) %>% 
  count(password, character) %>% 
  mutate_if(is.numeric, funs(replace_na(., 0))) %>% 
  arrange(password, character) %>%
  group_by(character) %>% 
  summarise(n = sum(n)) %>% 
  arrange(-n) %>% 
  mutate(rank = row_number()) %>% 
  ggplot(aes(x = rank, y = n)) +
  geom_line() + 
  geom_point() +
  scale_x_log10() + 
  scale_y_log10()
```

```{r}
#What words are most common when removing numbers? 
passwords %>% 
  select(password) %>% 
  mutate(password = str_replace_all(password, pattern = "[0-9]", "")) %>% 
  arrange(password) %>% 
  filter(password != "") %>% 
  count(password) %>% 
  filter(n > 1)
  
```


```{r}
#Lets find the most common first, second, and third letters 

passwords %>% 
  select(password) %>% 
  mutate(first = substr(password, 1, 1),
         second = substr(password, 2,2),
         third = substr(password, 3,3)) %>% 
  select(-password) %>% 
  gather(key = "positions", value = "letter") %>% 
  group_by(positions) %>% 
  count(letter) %>% 
  arrange(-n) %>% 
  ggplot(aes(x = letter, y = n, fill = positions)) + 
  geom_col() + 
  facet_wrap(~positions, scales = "free") + 
  theme(legend.position = "none")
```


```{r}
#Zips law for each position 
passwords %>% 
  select(password) %>% 
  mutate(first = substr(password, 1, 1),
         second = substr(password, 2,2),
         third = substr(password, 3,3)) %>% 
  select(-password) %>% 
  gather(key = "positions", value = "letter") %>% 
  group_by(positions) %>% 
  count(letter) %>% 
  arrange(positions, -n) %>% 
  mutate(rank = row_number()) %>% 
  ggplot(aes(x = rank, y = n, color = positions)) + 
  geom_line() + 
  scale_x_log10() + 
  scale_y_log10() 
```



```{r}
#Better Chart for First 3 letters 
passwords %>% 
  select(password) %>% 
  mutate(first = substr(password, 1, 1),
         second = substr(password, 2,2),
         third = substr(password, 3,3)) %>% 
  select(-password) %>% 
  gather(key = "positions", value = "letter") %>% 
  group_by(positions) %>% 
  count(letter) %>% 
  top_n(n, n = 5) %>% 
  ggplot(aes(x = reorder(letter, n), y = n, color = positions, group = positions)) + 
  geom_point() + 
  geom_segment(aes(xend = letter, yend = 0)) + 
  facet_wrap(~positions, scales = "free")
```

```{r}
#What are the most common first 3 letters combinations and their variations?  
passwords %>% 
  select(password) %>% 
  mutate(three = substr(password, 1, 3)) %>% 
  count(three) %>% 
  top_n(n, n = 5) %>% 
  select(three) %>% 
  inner_join(passwords %>% 
  select(password) %>% 
  mutate(three = substr(password, 1, 3))) %>% 
  arrange(three, password)

```

