---
title: "TidyTuesdayAppliedBusiness"
author: "Andrew Couch"
date: "1/14/2021"
output: html_document
---

Video: https://www.youtube.com/watch?v=VIJUVshbrgI&list=PLJfshcspBCYeJeO8YFT5e5HxuYOb5a_1W&index=7&t=186s

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(themis)

df <- read_csv("customer_churn.csv")
```


```{r}
df <- df %>% 
  drop_na() %>% 
  mutate(SeniorCitizen = as.factor(SeniorCitizen)) %>% 
  mutate_if(is.character, as.factor) %>% 
  mutate(Churn = fct_rev(Churn))

df %>% summary()
```


```{r}
# Create train and test splits
set.seed(42)
tidy_split <- initial_split(df, prop = .8, strata = Churn)
tidy_train <- training(tidy_split)
tidy_test <- testing(tidy_split)

tidy_k_folds <- vfold_cv(tidy_train)
```

```{r}
# Pre processing

tidy_rec <- recipe(Churn~., data = tidy_train) %>% 
  step_rm(customerID) %>% 
  step_BoxCox(all_numeric(), -all_outcomes()) %>% 
  step_normalize(all_numeric(), -all_outcomes()) %>% 
  step_dummy(all_nominal(), -all_outcomes(), one_hot = TRUE) %>% 
  step_downsample(Churn)

xgboost_model <- boost_tree(trees = tune(), tree_depth = tune()) %>% 
  set_mode("classification") %>% 
  set_engine("xgboost")

xgboost_grid <- grid_regular(parameters(xgboost_model), levels = 5, filter = c(trees > 1))

model_metrics <- metric_set(roc_auc, accuracy, mn_log_loss)
```


```{r}
xgboost_tune <- tune_grid(
  xgboost_model,
  tidy_rec,
  grid = xgboost_grid,
  resamples = tidy_k_folds,
  metrics = model_metrics
)
```


```{r}
xgboost_tune %>% 
  autoplot()
```


```{r}
xgboost_tune %>% show_best("accuracy", n = 1)
```


```{r}
final_model <- workflow() %>% 
  add_model(xgboost_model) %>% 
  add_recipe(tidy_rec) %>% 
  finalize_workflow(xgboost_tune %>% show_best("accuracy", n = 1))
```

```{r}
eval_df <- last_fit(final_model, tidy_split)
```

```{r}
eval_df %>% 
  collect_metrics()
```


```{r}
eval_df %>% 
  collect_predictions() %>% 
  conf_mat(truth = Churn, estimate = .pred_class)
```


```{r}
# Logic for `event_level`
event_col <- function(xtab, event_level) {
  if (identical(event_level, "first")) {
    colnames(xtab)[[1]]
  } else {
    colnames(xtab)[[2]]
  }
}

profit_est_vec <- function(truth, 
                          estimate, 
                          estimator = NULL, 
                          na_rm = TRUE, 
                          event_level = "first",
                          ...) {
  estimator <- finalize_estimator(truth, estimator)
  
  profit_est_impl <- function(truth, estimate) {
    # Create 
    xtab <- table(estimate, truth)
    col <- event_col(xtab, event_level)
    col2 <- setdiff(colnames(xtab), col)
    
    tp <- xtab[col, col]
    fn <- xtab[col2, col]
    tn <- xtab[col2, col2]
    fp <- xtab[col, col2]
    
    90*tp -100*fn + 5*tn -5*fp
  }
  
  metric_vec_template(
    metric_impl = profit_est_impl,
    truth = truth,
    estimate = estimate,
    na_rm = na_rm,
    cls = "factor",
    estimator = estimator,
    ...
  )
}
profit_est <- function(data, ...) {
  UseMethod("profit_est")
}

profit_est <- new_class_metric(profit_est, direction = "minimize")

profit_est.data.frame <- function(data, 
                                 truth, 
                                 estimate, 
                                 estimator = NULL, 
                                 na_rm = TRUE, 
                                 event_level = "first",
                                 ...) {
  metric_summarizer(
    metric_nm = "profit_est",
    metric_fn = profit_est_vec,
    data = data,
    truth = !! enquo(truth),
    estimate = !! enquo(estimate), 
    estimator = estimator,
    na_rm = na_rm,
    event_level = event_level,
    ...
  )
}
```

```{r}
eval_df %>% 
  collect_predictions() %>% 
  profit_est(truth = Churn, estimate = .pred_class)
```


```{r}
profit_max_df <- eval_df %>% 
  collect_predictions() %>% 
  select(.pred_Yes, Churn)
```

```{r}
maximize_profit <- function(prob){
  profit_max_df %>% 
    mutate(pred = if_else(.pred_Yes >= prob, "Yes", "No"),
           pred = as.factor(pred),
           pred = fct_relevel(pred, "Yes", "No")) %>% 
    profit_est(truth = Churn, estimate = pred) %>% 
    pluck(3)
}

tibble(prob = seq(0.01, .99, .01)) %>% 
  mutate(profit = map_dbl(prob, maximize_profit))
```

90*tp -100*fn + 5*tn -5*fp
```{r}
maximize_profit <- function(prob, TP = 90, FP = -5, TN = 5, FN = -100){
  profit_max_df %>% 
    mutate(pred = if_else(.pred_Yes >= prob, "Yes", "No")) %>% 
    count(pred, Churn) %>% 
    mutate(profit = case_when(
      pred == "Yes" & Churn == "Yes" ~ TP*n,
      pred == "Yes" & Churn == "No" ~ FP*n,
      pred == "No" & Churn == "No" ~ TN*n,
      T ~ FN*n
    )) %>% 
    summarise(profit = sum(profit)) %>% 
    pluck(1)
}

tibble(prob = seq(0.01, .99, .01)) %>% 
  mutate(profit = map_dbl(prob, maximize_profit),
         color = if_else(profit <= 0, "Loss", "Profit")) %>% 
  ggplot(aes(x = prob, y = profit)) +
  geom_hline(yintercept = 0, linetype = "dashed") + 
  geom_line() + 
  geom_point(aes(color = color)) 
```









