---
title: "TidyModelsEnsemble"
author: "Andrew Couch"
date: "10/13/2020"
output: html_document
---

Video: https://www.youtube.com/watch?v=44rINyxp220&list=PLJfshcspBCYeJeO8YFT5e5HxuYOb5a_1W&index=21&t=2s

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(AmesHousing)
library(stacks)
#remotes::install_github("tidymodels/stacks", ref = "main")

df <- make_ames()
```

# Train and Test Sets
```{r}
set.seed(13)

tidy_split <- initial_split(df, prop = .8)
tidy_train <- training(tidy_split)
tidy_test <- testing(tidy_split)

k_folds_data <- vfold_cv(tidy_train)
```


# Define Pre-processing
```{r}
pca_rec <- recipe(Sale_Price~., data = tidy_train) %>% 
  step_nzv(all_predictors()) %>% 
  step_corr(all_numeric(), -all_outcomes()) %>% 
  step_lincomb(all_numeric(), -all_outcomes()) %>% 
  step_other(all_nominal()) %>% 
  step_normalize(all_numeric(), -all_outcomes()) %>% 
  step_dummy(all_nominal()) %>% 
  step_pca(all_predictors(), num_comp = 5)
  
spline_rec <- recipe(Sale_Price~., data = tidy_train) %>% 
  step_nzv(all_predictors()) %>% 
  step_corr(all_numeric(), -all_outcomes()) %>% 
  step_lincomb(all_numeric(), -all_outcomes()) %>% 
  step_rm(all_nominal()) %>% 
  step_bs(all_predictors()) %>% 
  step_YeoJohnson(all_predictors())

tidy_rec <- recipe(Sale_Price~., data = tidy_train) %>% 
  step_nzv(all_predictors()) %>% 
  step_corr(all_numeric(), -all_outcomes()) %>% 
  step_lincomb(all_numeric(), -all_outcomes()) %>% 
  step_normalize(all_numeric(), -all_outcomes()) %>% 
  step_dummy(all_nominal()) 

```

# Define Models
```{r}
pca_regression_model <- linear_reg() %>% 
  set_mode("regression") %>% 
  set_engine("lm")

spline_model <- linear_reg() %>% 
  set_mode("regression") %>% 
  set_engine("lm")

randomForest_model <- rand_forest(min_n = tune(), trees = tune()) %>% 
  set_mode("regression") %>% 
  set_engine("randomForest")

xgboost_model <- boost_tree(learn_rate = tune(), trees = tune(), tree_depth = tune()) %>% 
  set_mode("regression") %>% 
  set_engine("xgboost")

```

# Define Tuning Control
```{r}
model_control <- control_grid(save_pred = TRUE, save_workflow = TRUE)
model_metrics <- metric_set(rmse, mae, rsq)
```

# Define Grids
```{r}

randforest_grid <- grid_regular(parameters(randomForest_model), levels = 3, filter = c(trees > 1))
xgboost_grid <- grid_regular(parameters(xgboost_model), levels = 3, filter = c(trees > 1))

```

# Define Workflows
```{r}
pca_wf <- workflow() %>% 
  add_model(pca_regression_model) %>% 
  add_recipe(pca_rec)

spline_wf <- workflow() %>% 
  add_model(spline_model) %>% 
  add_recipe(spline_rec)

randomForest_wf <- workflow() %>% 
  add_model(randomForest_model) %>% 
  add_recipe(tidy_rec)

xgboost_wf <- workflow() %>% 
  add_model(xgboost_model) %>% 
  add_recipe(tidy_rec)
```


# Fit models
```{r}

pca_res <- fit_resamples(
  pca_wf,
  resamples = k_folds_data,
  metrics = model_metrics,
  control = model_control
)

spline_res <- fit_resamples(
  spline_wf,
  resamples = k_folds_data,
  metrics = model_metrics,
  control = model_control
)

randomForest_res <- tune_grid(
  randomForest_wf,
  resamples = k_folds_data,
  grid = randforest_grid,
  metrics = model_metrics,
  control = model_control
)

xgboost_res <- tune_grid(
  xgboost_wf,
  resamples = k_folds_data,
  grid = xgboost_grid,
  metrics = model_metrics,
  control = model_control
)


```


```{r}
load("stack.Rdata")
```
# Create Stacks Model
```{r}


ames_stack <- stacks() %>% 
  add_candidates(pca_res) %>% 
  add_candidates(spline_res) %>% 
  add_candidates(randomForest_res) 

ames_stack <- ames_stack %>% 
  blend_predictions() %>% 
  fit_members()
```





# Finalize parameters 
```{r}
randomForest_final_param <- randomForest_res %>% show_best("rmse") %>% 
  slice(1) %>% 
  select(trees, min_n)

xgboost_final_param <- xgboost_res %>% 
  show_best("rmse") %>% 
  slice(1) %>% 
  select(trees:learn_rate)
```

# Collect model predictions to stack
```{r}
xgboost_stack <- xgboost_res %>% 
  collect_predictions() %>% 
  inner_join(xgboost_final_param) %>% 
  select(id, .row, Sale_Price, xgboost = .pred)

randomForest_stack <- randomForest_res %>% 
  collect_predictions() %>% 
  inner_join(randomForest_final_param) %>% 
  select(id, .row, randomforest = .pred)

pca_stack <- pca_res %>% 
  collect_predictions() %>% 
  select(id, .row, pca = .pred)

spline_stack <- spline_res %>%
  collect_predictions() %>% 
  select(id, .row, spline = .pred)
```

# Create ensemble data
```{r}
stack_df <- xgboost_stack %>% 
  left_join(randomForest_stack) %>% 
  left_join(pca_stack) %>% 
  left_join(spline_stack) %>% 
  select(-id, -.row)

stack_model <- linear_reg(penalty = .5, mixture = 1) %>% 
  set_mode("regression") %>% 
  set_engine("glmnet") %>% 
  fit(Sale_Price~., data = stack_df)

stack_model %>% tidy()
```

# Finalize submodels
```{r}
xgboost_wf <- xgboost_wf %>% 
  finalize_workflow(xgboost_final_param) %>% 
  last_fit(tidy_split)

randomForest_wf <- randomForest_wf %>% 
  finalize_workflow(randomForest_final_param) %>% 
  last_fit(tidy_split)

pca_wf <- pca_wf %>% last_fit(tidy_split)

spline_wf <- spline_wf %>% last_fit(tidy_split)

```


# Extract Predictions from Submodels
```{r}

stack_final_df <- tibble("model" = list(xgboost_wf, randomForest_wf, pca_wf, spline_wf),
                         "model_names" = c("xgboost", "randomforest", "pca", "spline")) %>% 
  mutate(pred = map(model, collect_predictions))

stack_final_df <- stack_final_df %>% 
  select(model_names, pred) %>% 
  unnest(pred) %>% 
  pivot_wider(names_from = model_names, values_from = .pred) %>% 
  select(-id, -.row) 
  
predict(stack_model, stack_final_df) %>% 
  bind_cols(stack_final_df) %>% 
  rename("stack" = .pred) %>% 
  pivot_longer(-Sale_Price) %>% 
  group_by(name) %>% 
  model_metrics(truth = Sale_Price, estimate = value) %>% 
  ungroup() %>% 
  pivot_wider(names_from = .metric, values_from = .estimate) %>% 
  arrange(rmse)
```


```{r}
predict(ames_stack, tidy_test) %>% 
  bind_cols(tidy_test %>% select(Sale_Price)) %>% 
  model_metrics(truth = Sale_Price, estimate = .pred) %>% 
  pivot_wider(names_from = .metric, values_from = .estimate)
```




