---
title: "TidyTuesdayDatabase"
author: "Andrew Couch"
date: "9/7/2020"
output: html_document
---

Video: https://www.youtube.com/watch?v=zAgTlZUugUE&list=PLJfshcspBCYeJeO8YFT5e5HxuYOb5a_1W&index=27

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(odbc)
library(DBI)
library(RSQLite)

fight <- read_csv("fight_data.csv")

con <- dbConnect(SQLite(), ":memory:")
copy_to(con, fight)
```

```{r}
dbGetQuery(con, '
SELECT * 
FROM FIGHT
           ')
```

```{r}

dbGetQuery(con, '
SELECT fight_pk, COUNT(fight_pk)
FROM FIGHT
GROUP BY fight_pk
ORDER BY COUNT(FIGHT_PK) DESC
           ')

```



```{r}
dbGetQuery(con, '
SELECT fight.fight_pk, fight.fighter, B.opponent, fight.res
FROM FIGHT
JOIN (SELECT fight_pk, fighter AS opponent FROM FIGHT) B
ON FIGHT.fight_pk = B.fight_pk
WHERE fight.fighter != B.opponent AND fighter > opponent
ORDER BY fight.fight_pk
           ')
```


```{r}
dbGetQuery(con, '
SELECT fight.fight_pk, fight.fighter, B.opponent, CASE WHEN 
fight.res = "W" THEN 1 ELSE 0 END AS fight_res
FROM FIGHT
JOIN (SELECT fight_pk, fighter AS opponent FROM FIGHT) B
ON FIGHT.fight_pk = B.fight_pk
WHERE fight.fighter != B.opponent AND fighter > opponent
ORDER BY fight.fight_pk
           ')
```

```{sql, connection = con, output.var = "df"}
SELECT fight.fight_pk, fight.fighter, B.opponent, CASE WHEN 
fight.res = "W" THEN 1 ELSE 0 END AS fight_res
FROM FIGHT
JOIN (SELECT fight_pk, fighter AS opponent FROM FIGHT) B
ON FIGHT.fight_pk = B.fight_pk
WHERE fight.fighter != B.opponent AND fighter > opponent
ORDER BY fight.fight_pk
```

```{r}
df
```

```{r}

fight_db <- tbl(con, "fight")

fight_query <- fight_db %>% 
  select(fighter, fight_pk, res) %>% 
  left_join(fight_db %>% select(fight_pk, opponent = fighter), by = "fight_pk") %>% 
  filter(fighter != opponent & fighter > opponent) %>% 
  mutate(res = if_else(res == "W", 1, 0))

fight_query %>% show_query()

```



```{sql, connection = con}
SELECT `fighter`, `fight_pk`, CASE WHEN (`res` = 'W') THEN (1.0) WHEN NOT(`res` = 'W') THEN (0.0) END AS `res`, `opponent`
FROM (SELECT `LHS`.`fighter` AS `fighter`, `LHS`.`fight_pk` AS `fight_pk`, `LHS`.`res` AS `res`, `RHS`.`opponent` AS `opponent`
FROM (SELECT `fighter`, `fight_pk`, `res`
FROM `fight`) AS `LHS`
LEFT JOIN (SELECT `fight_pk`, `fighter` AS `opponent`
FROM `fight`) AS `RHS`
ON (`LHS`.`fight_pk` = `RHS`.`fight_pk`)
)
WHERE (`fighter` != `opponent` AND `fighter` > `opponent`)
```


```{r}
dbDisconnect(con)
```

```{r}
library(elo)

elo_model <- elo.run(fight_res ~ fighter + opponent, data = df, k = 20)

bind_rows(elo_model %>% as.data.frame() %>% select(team.A, elo.A) %>% rename_all(.funs = ~str_replace(.x, ".A", "")) %>% bind_cols(df %>% select(fight_pk)),
          elo_model %>% as.data.frame() %>% select(team.B, elo.B) %>% rename_all(.funs = ~str_replace(.x, ".B", ""))%>% bind_cols(df %>% select(fight_pk))) %>% 
  group_by(team) %>% 
  arrange(fight_pk) %>% 
  mutate(fight_number = row_number()) %>% 
  ungroup() %>% 
  ggplot(aes(x = fight_number, y = elo, group = team)) + geom_line(alpha = .4)

```



